### ISSUE TITLE
User position on leaderboard

### ISSUE THREAD

**Issue by Flaming-Galaxy** [Q-Sharp/BattleBot#23]
**Describe the bug**
Users not in the top 5 on the rp leaderboard will not show when the command is called. Users searched for will not show on the leaderboard either.

**To Reproduce**
1. Use command "b!p lb @<user not in top 5>"
2. Leaderboard of top 5 users will show

**Expected behavior**
Top 5 users and then rank about user searched for, the user and then the user ranked one below.

**What platform are you using discord on?**
Desktop application.

**Comment by Greenfoot5** [comment]
This feature was never re-added when profiles were changed to save into json files. Mostly because I forgot.
