### ISSUE TITLE
Improved Levels

### ISSUE THREAD

**Issue by Greenfoot5** [Q-Sharp/BattleBot#41]
**Please describe what you'd like the bot to do**
Have a better level system. With more features, better rewards and more.

**Why should the bot do this?**
The current rank system is very flat, and boring. Adding rewards, increasing the formula at later levels and a reset would help with this.

**Additional context**
Potential rewards:

- Rank colours
- Access to bonus commands
- Extra customisation on their profile
- Achievements
- Access to clans

**Comment by Greenfoot5** [comment]
This should also include #34 completion.

**Comment by Q-Sharp** [comment]
> actually roles for 0,5,10,15,20,25,30,35,40,45,50
> 0 Village, 5 Battlegrounds, 10 Bandit Town, 15 Iron Ramparts, 20 Soldiers' Encampment, 25 Royal Encampment, 30 Uncharted Jungle, 35 Sky Temple, 40 Arcane Desert, 45 Ancient Tomb, 50 Eldricht Mountains
> 
> Something like that would be cool imo
> 
> and then add more levels; 55 Divine Sanctuary, 60 Whispering Ruins, 65 Druidic Forest, 70 Valley of Giants
> cause 50 is max atm, right?
@XitraQ#4396
